version: '3.1'

services:
  mysql:
    image: 'mysql:8.0'
    command: '--authentication_policy=mysql_native_password'
    container_name: sas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  buggregator:
    image: ghcr.io/buggregator/server:latest
    container_name: sas-buggregator
    ports:
      - 8000:8000
      - 1025:1025
      - 9912:9912
      - 9913:9913
#    environment:
#      VIRTUAL_HOST: buggregator.bc.local
#      VIRTUAL_PORT: 8000

  app:
    build: ./docker/roadrunner
    entrypoint: /docker-entrypoint.sh
    container_name: sas-app
    working_dir: /srv
    volumes:
      - ./src/app:/srv
      - ./docker/roadrunner/entrypoint.sh:/docker-entrypoint.sh:ro
    environment:
      PHP_IDE_CONFIG: serverName=app

volumes:
  mysql: ~
