version: "3"

rpc:
  listen: tcp://0.0.0.0:6001

server:
  command: "php app.php"
  relay: pipes

kafka:
  brokers: [ kafka:9092 ]

jobs:
  pool:
    debug: true
    command: "php app.php"
    num_workers: 1
  consume:
    - kafka_test
  pipelines:
    kafka_test:
      driver: kafka
      config:
        consumer_options:
          topics: [ "kafka_test" ]
          consume_regexp: false
        group_options:
          group_id: rr_consumer

logs:
  mode: development
  level: debug
  encoding: console
