version: "3"

rpc:
  listen: tcp://0.0.0.0:6001

server:
  command: "php app.php"
  relay: pipes

kafka:
  brokers: [ kafka:9092 ]

jobs:
  pool:
    debug: true
    command: "php app.php"
    num_workers: 1
  pipelines:
    kafka_test:
      driver: kafka
      config:
        auto_create_topics_enable: true

logs:
  mode: development
  level: debug
  encoding: console
