version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

kafka:
  brokers: [ "kafka:9092" ]

server:
#  command: "php app.php"
  command: "php -d xdebug.client_host=172.20.0.1 -d memory_limit=-1 app.php"
  env:
    - XDEBUG_CONFIG: idekey='PHPSTORM'
    - XDEBUG_MODE: debug

http:
  pool:
    num_workers: 1
    debug: true
  address: 0.0.0.0:8080
  middleware: [ "otel" ]
  otel:
    insecure: true
    compress: false
    client: http
    exporter: otlp
    service_name: be-pub
    service_version: 0.1.0
    endpoint: otel-collector:4318


jobs:
  pool:
    command: "php app.php"
    num_workers: 1
    debug: false
  consume:
    - local
  pipelines:
    local:
      driver: "memory"
      config:
        priority: 9
        prefetch: 3
    # produce
    kafka_produce:
      driver: kafka
      config:
        auto_create_topics_enable: true
        topic: "sas.foo-bar"

logs:
  mode: development
  level: debug
  encoding: console
