version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

kafka:
  brokers: [ "kafka:9092" ]

server:
#  command: "php app.php"
  command: "php -d xdebug.client_host=172.20.0.1 -d memory_limit=-1 app.php"
  env:
    - XDEBUG_CONFIG: idekey='PHPSTORM'
    - XDEBUG_MODE: debug

#otel:
#  resource:
#    service_name: "rr_app_producer"
#    service_version: "1.0.0"
#    service_namespace: "spiral-app-sandbox"
#    service_instance_id: "UUID"
#  insecure: true
#  compress: false
#  exporter: otlp
#  endpoint: collector:4318

http:
  pool:
    num_workers: 1
    debug: true
  address: 0.0.0.0:8080
#  middleware: [ "otel" ]

jobs:
  pool:
    command: "php -d xdebug.client_host=172.20.0.1 -d memory_limit=-1 app.php"
    num_workers: 1
  consume:
    - local
  pipelines:
    local:
      driver: "memory"
      config:
        priority: 9
        prefetch: 3
    # produce
    kafka_produce:
      driver: kafka
      config:
        auto_create_topics_enable: true
        topic: "sas.foo-bar"

kv:
  local:
    driver: memory
    config: { }

fileserver:
  address: 0.0.0.0:10101
  calculate_etag: true
  weak: false
  stream_request_body: true
  serve:
    - prefix: "/"
      root: "./runtime/static"

logs:
  mode: development
  level: debug
  encoding: console
