version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app.php"
  relay: pipes

jobs:
  pool:
    command: "php app.php"
    num_workers: 7
    debug: false

logs:
  mode: development
  level: debug
  encoding: console
